/**
 * @file    threshold_lut.h
 * @brief   Amplitude threshold LUT — one entry per A121 radar point.
 *
 * Auto-generated by generate_threshold_lut.py on 2026-03-22 14:47:59
 * DO NOT EDIT MANUALLY — regenerate using the Python tool.
 *
 * Sensor config used to generate:
 *   CONFIG_STEP       = 3
 *   CONFIG_START_POINT= 0
 *   rf_factor         = 1.47
 *   Step size         = 7.5000 mm/point
 *   Distance range    = 0.00 .. 2035.71 mm
 *   Entries           = 400  (1600 bytes in flash)
 *
 * Firmware indexing:
 *   lut[i] corresponds directly to data[i] from acc_algorithm.
 *   No index conversion needed — compare amplitudes[i] > g_threshold_lut[i].
 *
 * Breakpoints used:
 *        0.00 mm  ->  400000
 *       40.00 mm  ->  100000
 *      100.00 mm  ->  50000
 *      240.00 mm  ->  500
 *      400.00 mm  ->  300
 *      600.00 mm  ->  200
 *      900.00 mm  ->  100
 *
 * NOTE: Array definition lives in threshold_lut.c (stored once in flash).
 */

#ifndef THRESHOLD_LUT_H
#define THRESHOLD_LUT_H

#include <stdint.h>

#define THRESHOLD_LUT_LEN        400U
#define THRESHOLD_LUT_STEP_MM    7.5000f
#define THRESHOLD_LUT_START_MM   0.0000f
#define THRESHOLD_LUT_END_MM     2035.7143f

extern const uint32_t g_threshold_lut[THRESHOLD_LUT_LEN];

#endif /* THRESHOLD_LUT_H */
